### ISSUE TITLE
Remove Curl

### ISSUE THREAD

**Issue by seanlaw** [louisabraham/pydivsufsort#1]
@louisabraham Is there a reason why we are downloading the libdivsufsort from its primary Github repo? Considering:

1. The license is an MIT license which is compatible with your current license 
2. There hasn't been any changes to the libdivsufsort repo in at least 5 years (i.e., it is stable and any future change is likely to be small or have little affect on this package)

I propose that, for simplicity and to make everything self contained, we just include libdivsufsort directly inside of this package. This also avoids needing curl (which may or may not be available everywhere). Any thoughts?

**Comment by louisabraham** [comment]
I just don't know how to put them in a sdist and exclude them from a wheels. But `build.sh` has the same issue. Can you add libdivsufsort as a submodule and change `build.sh` accordingly?

**Comment by seanlaw** [comment]
You'll have to excuse my lack of understanding when it comes to sdist and wheels but what is the reason that we need to exclude them from wheels? Aside from size/bloat would having them in the wheel cause conflicts or prevent the library from functioning? If not (i.e., it's just bloat), then perhaps we can be pragmatic and allow the bloat for now and create a new issue to fix the bloat in the future (and possibly get help from others)

**Comment by louisabraham** [comment]
You are right. Anyway, I don't think a sdist can be made as one needs gcc and cmake, so it doesn't matter.

**Comment by louisabraham** [comment]
Fixed by submodules in 89dcb7f3da45bfcfae940858b2bc9d3bb40541e1
