### ISSUE TITLE
LCP array computation

### ISSUE THREAD

**Issue by louisabraham** [louisabraham/pydivsufsort#14]
Kasai's algorithm can be used (leading to a 13n memory requirement).

A function to count occurrences of a pattern can be implemented as well: https://en.wikipedia.org/wiki/LCP_array#LCP_array_usage_in_finding_the_number_of_occurrences_of_a_pattern

**Comment by louisabraham** [comment]
An implementation in C / Cython should be preferred (even over numba) for performance concerns.

**Comment by seanlaw** [comment]
> An implementation in C / Cython should be preferred (even over numba) for performance concerns.

I think the Kasai version that you have is great!

**Comment by louisabraham** [comment]
Cython's [fused types](https://cython.readthedocs.io/en/latest/src/userguide/fusedtypes.html) are awesome for supporting a lot of types.

**Comment by louisabraham** [comment]
Strange, the same code can build or not build on arm64

build: https://travis-ci.org/louisabraham/pydivsufsort/jobs/658782740
fail: https://travis-ci.org/louisabraham/pydivsufsort/jobs/658789600
diff: https://github.com/louisabraham/pydivsufsort/compare/8cec34f9d0d1...830035ac564e

**Comment by seanlaw** [comment]
In Kasai's algorithm, would it be possible to add an optional function argument called `stop` like:

```
def kasai(inp, sa, stop=None):
```

Where `stop` represents the sentinel integer (say, zero) and in this check:

```
while i + k < n and j + k < n and s[i + k] == s[j + k]:
    k += 1
```

it would change to something like:

```
while i + k < n and j + k < n and s[i + k] != stop and s[j + k] != stop and s[i + k] == s[j + k]:
    k = k + 1
```

Essentially, I'm only interested in counting the overlap between neighboring sequences but stopping (and excluding) the sentinel integer.

**Comment by louisabraham** [comment]
I'm not 100% sure it is still a correct algorithm.

What you could do is build a second array that contains the "distance" to the next separator (computable in linear time with a simple loop going backwards). Then you build an array that tells for every 2 neighbors of the suffix array the minimum of their distances to their next separators. Finally you take the minimum of that array and the LCP array.
It is a linear time algorithm with few branchings and a lot of efficient operations that can be vectorised by the compiler so it will be really fast.

I can implement it as a separate algorithm but I'm against modifying Kasai's algorithm: it will complexify the interface and I am not even sure it is correct.

**Comment by seanlaw** [comment]
@louisabraham I agree with you 100% that what I'm proposing is not Kasai's algorithm. It's a modification of it. My only hope was to avoid taking a second pass over the sorted suffixes. 

I am totally open to a separate set of functions that implements what you propose as long as I can easily get to this output:

```
[0 0 0 0 0 1 1 1 1 3 3 2 3 0 3 0 1 0 2 2 1 2 0]
```

**Comment by seanlaw** [comment]
> What you could do is build a second array that contains the "distance" to the next separator (computable in linear time with a simple loop going backwards). Then you build an array that tells for every 2 neighbors of the suffix array the minimum of their distances to their next separators. Finally you take the minimum of that array and the LCP array.

Btw, I really like your suggestion! I'm impressed by your creative thinking and your ability to thoughtfully consider time complexity. I appreciate all of these things when it is presented to me but I wished that my brain were wired like that!

**Comment by louisabraham** [comment]
> I agree with you 100% that what I'm proposing is not Kasai's algorithm. It's a modification of it. My only hope was to avoid taking a second pass over the sorted suffixes in order to get to my desired output.

What I meant is that I was not sure that this modification is correct, but now I am convinced it is.

My solution allows you to do it without separators.

If you want to separate n+1 strings, why not just use n different separators? It will change slightly the suffix array when the comparison of two suffixes breaks down after separators. However, since you don't care about the result when a separator is met, I think you will get an equivalent LCP array with the standard Kasai algorithm.
The disavantage is that you might use more bits if your base alphabet is small and n is big, so divsufsort will use more time.

Overall, I'm against including a non standard version of Kasai's algorithm when the same result can be achieved costlessly.
I think you should not worry about doing a second pass, it's a very fast linear algorithm with a negligible cost compared to divsufsort or even Kasai's.

**Comment by seanlaw** [comment]
> If you want to separate n+1 strings, why not just use n different separators? It will change slightly the suffix array when the comparison of two suffixes breaks down after separators. However, since you don't care about the result when a separator is met, I think you will get an equivalent LCP array with the standard Kasai algorithm.

Ohhhh, I see what you mean now! I have seen people using different separators (without explaining why) but I hadn't considered the value of having different separators until now. That makes sense. 

> Overall, I'm against including a non standard version of Kasai's algorithm when the same result can be achieved costlessly.

I'm with you. Let me try modifying my input as you proposed. That might be good enough

**Comment by louisabraham** [comment]
Else, you can still implement my method in pure numpy. To build the first array of "distances", you can use cumsum.

**Comment by louisabraham** [comment]
This is now implemented in Cython and has been pushed in version 0.0.2.
The setup.py doesn't make any sense (have to use distutils from setuptools) but hey it works.
