### ISSUE TITLE
Problem Linking Library Generically On Mac OS X

### ISSUE THREAD

**Issue by seanlaw** [louisabraham/pydivsufsort#2]
@louisabraham I tried following your instructions and it seemed to build and install without any issues. However, I can't seem to import the package:

```
python ./example.py
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
~/Git/pydivsufsort.git/examples/example.py in <module>
      4 import numpy as np
      5
----> 6 from pydivsufsort import divsufsort
      7
      8

~/miniconda3/lib/python3.7/site-packages/pydivsufsort/__init__.py in <module>
----> 1 from .divsufsort import divsufsort

~/miniconda3/lib/python3.7/site-packages/pydivsufsort/divsufsort.py in <module>
      4 import numpy as np
      5
----> 6 from .dll import libdivsufsort, libdivsufsort64
      7
      8

~/miniconda3/lib/python3.7/site-packages/pydivsufsort/dll.py in <module>
      4 PATH = Path(__file__).parent
      5
----> 6 PATH_LIBDIVSUFSORT = next(PATH.glob("libdivsufsort.so*"))
      7 PATH_LIBDIVSUFSORT64 = next(PATH.glob("libdivsufsort64.so*"))
      8

StopIteration:
```

**Comment by seanlaw** [comment]
I did a little digging but it looks like there are a couple of possible issues:

1. On a Mac, the files are called `libdivsufsort.3.0.1.dylib` and `libdivsufsort64.3.0.1.dylib` and the `build.sh` successfully copies them into the `pydivsufsort` directory but I'm not sure that `dll.py` would reference them correctly
2. When I actually look into the `~/miniconda3/lib/python3.7/site-packages/pydivsufsort` I don't see the `libdivsufsort.3.0.1.dylib` and `libdivsufsort64.3.0.1.dylib` files in the same directory.

After I manually moved `libdivsufsort.3.0.1.dylib` and `libdivsufsort64.3.0.1.dylib` into `~/miniconda3/lib/python3.7/site-packages/pydivsufsort` and ran the `example.py` then I get:

```
python ./example.py
[5 3 1 0 4 2]
Segmentation fault: 11
```
It looks like it like:

```
print(divsufsort(array.array('B', [98, 97, 110, 97, 110, 97])))
```

But commenting this above line out allows the entire file to run without segfaulting!

We probably need to change change this line in `setup.py` from:
`package_data={'pydivsufsort': ['libdivsufsort.so*', 'libdivsufsort64.so*']},`
to
`package_data={'pydivsufsort': ['libdivsufsort.*', 'libdivsufsort64.*']},`

**Comment by seanlaw** [comment]
@louisabraham You beat me to it! I was just about to submit a PR :)

**Comment by louisabraham** [comment]
I also fixed the segfault on array.array: macos probably doesn't like manual pointers.

```diff
-        addr, _ = inp.buffer_info()
-        inp_p = addr
+        inp = (ctypes.c_uint8 * len(inp)).from_buffer(inp)
+        inp_p = ctypes.byref(inp)
```
