### ISSUE TITLE
Cython Dependency in Setup.py Breaking Installation

### ISSUE THREAD

**Issue by seanlaw** [louisabraham/pydivsufsort#23]
I think we have a `chicken and the egg situation". I performed a fresh install of my Python environment (with Conda) and when I try:

```
python -m pip install .
```

I am met with:

```
    ERROR: Command errored out with exit status 1:
     command: /Users/law978/miniconda3/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/32/vghdf9rd4w1b2s9cpkf2v9nrcbdy1n/T/pip-req-build-tp5rjpyx/setup.py'"'"'; __file__='"'"'/private/var/folders/32/vghdf9rd4w1b2s9cpkf2v9nrcbdy1n/T/pip-req-build-tp5rjpyx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/32/vghdf9rd4w1b2s9cpkf2v9nrcbdy1n/T/pip-req-build-tp5rjpyx/pip-egg-info
         cwd: /private/var/folders/32/vghdf9rd4w1b2s9cpkf2v9nrcbdy1n/T/pip-req-build-tp5rjpyx/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/32/vghdf9rd4w1b2s9cpkf2v9nrcbdy1n/T/pip-req-build-tp5rjpyx/setup.py", line 10, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It looks like `setup.py` itself is dependent on `cython` having already been installed. But, at the same time, it is not sufficient to add `cython` as a dependency in the `setup.py`. Normally, `setup.py` would have installed `cython` first but `cython` is being imported at the top of the file. I'm not sure what the best way to fix this would be aside from removing `cython` from the top of the `setup.py` script. This also implies that installing from PyPI via `pip install pydivsufsort` would also fail if `cython` is not already installed but, naturally, this should be handled by `setup.py`.

**Comment by seanlaw** [comment]
Of course, after manually installing `cython` first, then `python -m pip install .` works fine

**Comment by seanlaw** [comment]
Okay, I spoke too soon. There must've been a change in the last commit as while `python -m pip install .` appears to install without any errors, pytest fails with:

```
============================= test session starts ==============================
platform darwin -- Python 3.7.1, pytest-5.4.1, py-1.8.1, pluggy-0.13.0
rootdir: /Users/law978/Git/pydivsufsort.git
plugins: cov-2.8.1
collected 0 items / 1 error

==================================== ERRORS ====================================
____________________ ERROR collecting tests/test_correct.py ____________________
tests/test_correct.py:7: in <module>
    from pydivsufsort import divsufsort
../../miniconda3/lib/python3.7/site-packages/pydivsufsort/__init__.py:1: in <module>
    from .divsufsort import divsufsort
../../miniconda3/lib/python3.7/site-packages/pydivsufsort/divsufsort.py:7: in <module>
    from .dll import libdivsufsort, libdivsufsort64
../../miniconda3/lib/python3.7/site-packages/pydivsufsort/dll.py:12: in <module>
    PATH_LIBDIVSUFSORT = next(PATH.glob("libdivsufsort.*"))
E   StopIteration
=========================== short test summary info ============================
ERROR tests/test_correct.py - StopIteration
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.26s ===============================
```

However, reinstalling with `python -m pip install pydivsufsort` is fine and the tests pass. But this syntax for installing seems atypical and I'd much prefer `python -m pip install .`

**Comment by louisabraham** [comment]
It looks like `python -m pip install .` doesn't compile libdivsufsort.

The structure of the setup.py is far from optimal but after hundreds (really) of attempts it works on Travis so I'm not willing to change it.

 99% of users will just install the wheels through pypi so I think it is fine.

About the current failures on Travis, we just have to wait for manylinux to fix them https://github.com/pypa/manylinux/issues/512

**Comment by seanlaw** [comment]
> The structure of the setup.py is far from optimal but after hundreds (really) of attempts it works on Travis so I'm not willing to change it.

That's fair. Would it bother you if I added a `setup.sh` file to the root directly that has `python -m pip install pydivsufsort` in there and maybe a check for `cython`? This way, manual installation is straightforward when we come back to it months from now when we don't have any muscle memory. Your call. 

> 99% of users will just install the wheels through pypi so I think it is fine.

Ahh, gotcha! With wheels, the `cython` issue is automatically handled

**Comment by seanlaw** [comment]
Should I add `cython` to the `setup.py` as a requirement?  I can also add a `requirements.txt`

**Comment by louisabraham** [comment]
I think adding a requirements.txt would be the most standard way. Don't forget to add numpy as well.

**Comment by louisabraham** [comment]
@seanlaw what is setup.sh from 8920c3a? I think we should remove it.

**Comment by seanlaw** [comment]
@louisabraham Due to the fact that installing from source is non-standard (i.e., using `python -m pip install pydivsufsort` instead of `python -m pip install .`) and, for development, I tend to either create isolated virtual environments or sometimes start my environments from scratch, this script is there to make it easier to install the package from source. This avoids having to:

1. Remember to uninstall pydivsuvsort first if it is already installed (if I had previously installed the package via PyPI but now I want to install locally from source for development purposes)
2. Remember to install requirements
3. Remember to read the README and to use `python -m pip install pydivsufsort` instead of `python -m pip install .`

This single script allows me to not care and know that everything is install from local source

**Comment by louisabraham** [comment]
I think `python -m pip install pydivsufsort` does **not** install from source.

This script will probably confuse other people though so I would like to remove it.

**Comment by seanlaw** [comment]
> I think python -m pip install pydivsufsort does not install from source.

Okay, I think I overlooked that since, originally, I could only install from source when we first started and then, at some point, you had added it to PyPI. So, what command does one use to install from source?

**Comment by seanlaw** [comment]
> This script will probably confuse other people though so I would like to remove it.

I'm fine with that

**Comment by louisabraham** [comment]
> So, what command does one use to install from source?

    python -m pip install .

**Comment by seanlaw** [comment]
But that takes us back to the problem that we had in the first place and why this issue was raised. Has something changed to fix the original issue and allow this command to work properly now?

**Comment by louisabraham** [comment]
I think the following would work:

    python -m pip install -r requirements.txt
    python -m pip install -U .

**Comment by seanlaw** [comment]
This is a rather nasty problem with using `cythonize` (and it looks like [you had encountered this previously too](https://github.com/pypa/setuptools/issues/1317)).

Let's close it as there is no shortcut to make this work elegantly

**Comment by louisabraham** [comment]
Haha yes it's always funny to rediscover issues from the past. A lot of repositories have the same issue, and most of our users won't have it since we prebuild wheels.

**Comment by seanlaw** [comment]
I had a scenario where I had to install from source so I'm leaving the installation instructions here for posterity:

```
MINICONDAPREFIX=`pwd`/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash ./Miniconda3-latest-Linux-x86_64.sh -b -p $MINICONDAPREFIX
export PATH="$MINICONDAPREFIX/bin:$PATH"
export LD_LIBRARY_PATH="$MINICONDAPREFIX/lib"
conda update -y conda
conda update -y --all
conda install -y -c conda-forge gcc_linux-64 gxx_linux-64 numpy cython pytest cmake
ln -s $MINICONDAPREFIX/bin/x86_64-conda_cos6-linux-gnu-gcc $MINICONDAPREFIX/bin/gcc
ln -s $MINICONDAPREFIX/bin/x86_64-conda_cos6-linux-gnu-g++ $MINICONDAPREFIX/bin/g++

cd Git
git clone --recurse-submodules https://github.com/louisabraham/pydivsufsort.git ./pydivsufsort.git
cd ./pydivsufsort.git
./build.sh
python -m pip install .

cd tests
pytest test_py
```
