### ISSUE TITLE
rename divsufsort() and kasai() ?

### ISSUE THREAD

**Issue by louisabraham** [louisabraham/pydivsufsort#25]
@seanlaw I think some users would prefer to have functions simply named `suffix_array()` and `lcp_array()`. Maybe providing aliases can be useful.

**Comment by seanlaw** [comment]
I 100% agree with you! I think it is far more explicit so I support the idea of aliasing. Let me know and I will update the README examples accordingly

By "aliasing", I am assuming you don't mean `from pydivsufsort import kasai as lcp_array`

**Comment by seanlaw** [comment]
Alternatively, you could change `kasai()` to a private function `_kasai` and just have `lcp_array` call `_kasai`. Just a thought

**Comment by louisabraham** [comment]
I think it's better not to change that, kasai and divsufsort refer to the implementation.

The higher level interface discussed in other issues will call them `.lcp_array` and `.suffix_array`.
