### ISSUE TITLE
implement an index class

### ISSUE THREAD

**Issue by louisabraham** [louisabraham/pydivsufsort#26]
It computes the suffix array, lcp array and segment tree lazily and allows to answer LCP and search queries.
Furthermore, it can be easily serialized using pickle.

**Comment by seanlaw** [comment]
Does this mean that you be using Python’s `@property` decorator for this lazy computation?

**Comment by louisabraham** [comment]
property is just a syntactic sugar. memoization is the algorithm.

What about WonderString for the name of this class and the new repository name?

**Comment by seanlaw** [comment]
I think the issue with using the word “String” in the name is that it immediately makes people assume that it only works for strings (which is not my use case).

**Comment by louisabraham** [comment]
I think it's not a big problem as "string" refers more to a family of algorithms that can be used on arrays than to the `str` datatype. For example, the Wikipedia [page](https://en.wikipedia.org/wiki/Suffix_array) of suffix arrays talks about strings.

**Comment by seanlaw** [comment]
I think that is fair assuming that we supply examples where integers can be used (which we have in the README). 

I am curious why the “Wonder” part?

**Comment by louisabraham** [comment]
I like superheroes and I was not comfortable with the acronym SS. Also, a reference to a female superhero is not bad in the world of computer science where men are over represented.

**Comment by seanlaw** [comment]
Cool. I’m down for that

**Comment by louisabraham** [comment]
Done.
