### ISSUE TITLE
Failing With np.uint64 Array

### ISSUE THREAD

**Issue by seanlaw** [louisabraham/pydivsufsort#3]
When I try to explore a different array such as:

```
random_string = np.random.randint(10000, size=100_000_000, dtype=np.uint64)
```

I am encountering:

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
~/Git/pydivsufsort.git/examples/example.py in <module>
     15 d = time()
     16 for _ in range(100):
---> 17     np.array(divsufsort(random_string))
     18 print(time() - d)
     19

~/miniconda3/lib/python3.7/site-packages/pydivsufsort/divsufsort.py in divsufsort(inp)
      9 def divsufsort(inp):
     10     if isinstance(inp, np.ndarray):
---> 11         assert inp.dtype == np.uint8
     12         if not inp.flags["C_CONTIGUOUS"]:
     13             # Make a contiguous copy of the numpy array.

AssertionError:
```

**Comment by louisabraham** [comment]
This is normal, libdivsufsort doesn't support an other type than char.

**Comment by louisabraham** [comment]
I could support other types using either sais.hxx by Yuta Mori or just encoding the letters as char. If anybody needs that, please reopen the issue.

**Comment by seanlaw** [comment]
Actually, this is my use case. My input is always a NumPy array of ints where there could be 10K or more unique ints and over a billion elements in length. My input is never char and will certainly be more than `np.uint8`

**Comment by louisabraham** [comment]
Ok, I'll implement both solutions and benchmark them tomorrow.

Basically, you can just encode a value by putting its bytes in the suffix array. For your example, 2 bytes per value are sufficient. After that, you can just take the even values of the output.

**Comment by seanlaw** [comment]
Sounds good! Looking forward to it

**Comment by louisabraham** [comment]
Now fixed!

**Comment by louisabraham** [comment]
I didn't implement the sais.hxx solution, it is probably slower. Note that a type that uses k bits will need approximately k more time so try to use the smallest type you can. I can  add later a function that transform the input to the smallest dtype.
