### ISSUE TITLE
Follow Python Install Best Practice

### ISSUE THREAD

**Issue by seanlaw** [louisabraham/pydivsufsort#4]
According to Brett Cannon (who is on the Python Steering Council), he strongly advocates for using `python -m pip install .` instead of `pip install .`

You can read more about the reasoning and rationale [here on his blog](https://snarky.ca/why-you-should-use-python-m-pip/). I propose that we update the README to reflect this. I've done the same in STUMPY

**Comment by louisabraham** [comment]
Sure, I knew about it. The current README is intended for the contributors, it will be updated when the project is a bit more mature.
