### ISSUE TITLE
allow bwt on non-ascii

### ISSUE THREAD

**Issue by eyaler** [louisabraham/pydivsufsort#40]
in my use case i want to do bwt on utf8 strings. i do not want to utf8 encode them into bytes, as dealing with the broken point codes is weird and i would like keep the symbols intact. therefore i would like to be able to use an int32 list.

**Comment by louisabraham** [comment]
This should be pretty simple to implement in naive python.

Let (idx, U) be the output, T be the input and A be the suffix array.

from https://github.com/lh3/libdivsufsort/blob/master/lib/utils.c#L96-L99=
```
    U[0] = T[n - 1];
    for(i = 0; A[i] != 0; ++i) { U[i + 1] = T[A[i] - 1]; }
    *idx = i + 1;
    for(++i; i < n; ++i) { U[i] = T[A[i] - 1]; }
```

Basically it's that slide with a special case for `$`.
<img width="670" alt="image" src="https://user-images.githubusercontent.com/13174805/178174835-328c0ff3-c75a-44b4-a10a-9abb0a9e968b.png">

I will probably recode it in Cython some day.

**Comment by eyaler** [comment]
thanks! for now i am just doing something like:
```
sa = divsufsort(np.array([ord(c) for c in text]))
trans = ''.join(text[sa[i] - 1] for i in range(len(sa)))
index = list(sa).index(0)
```
btw, why in your BWT are you moving the eos to the beginning?

**Comment by louisabraham** [comment]
Yeah I think it is the best solution for now.

Very good question, I just copied the relevant lines from libdivsufsort. No idea why they do it like that.

**Comment by louisabraham** [comment]
clsoing this for inactivity
