### ISSUE TITLE
Support Mac M1 chip?

### ISSUE THREAD

**Issue by jalew188** [louisabraham/pydivsufsort#45]
Thank you for this cool library. 

In Mac M1, it raised an error:
```
File ~/opt/miniconda3/lib/python3.9/site-packages/pydivsufsort/dll.py:15
     13     PATH_LIBDIVSUFSORT64 = find_dll("divsufsort64.dll")
     14 else:
---> 15     PATH_LIBDIVSUFSORT = next(PATH.glob("libdivsufsort.*"))
     16     PATH_LIBDIVSUFSORT64 = next(PATH.glob("libdivsufsort64.*"))
     18 libdivsufsort = ctypes.CDLL(PATH_LIBDIVSUFSORT)

StopIteration: 
```

**Comment by samuelhorwitz** [comment]
I have the same problem. A temporary fix that seems to work for me is:

1. `brew install libdivsufsort`
2. Change `PATH_LIBDIVSUFSORT = "/path/to/homebrew/Cellar/libdivsufsort/2.0.1/lib/libdivsufsort.3.0.0.dylib"` and `PATH_LIBDIVSUFSORT64 = "/path/to/homebrew/Cellar/libdivsufsort/2.0.1/lib/libdivsufsort64.3.0.0.dylib"` in dll.py, wherever you installed pydivsufsort.

**Comment by louisabraham** [comment]
Hi, currently, the wheels are generated by cibuildwheel running on Github Actions. Github Actions don't support m1 machines yet, however cibuildwheel allows [cross-compilation](https://cibuildwheel.readthedocs.io/en/stable/faq/#how-to-cross-compile).  I just edited the yml and relaunched the jobs. Let's see!

**Comment by louisabraham** [comment]
It is my pleasure to announce that macosx arm64 pre-compiled wheels are available on pypi: https://pypi.org/project/pydivsufsort/#files

**Comment by jalew188** [comment]
Thanks a lot @louisabraham

**Comment by louisabraham** [comment]
@jalew188 does it work for you?

**Comment by GeorgWa** [comment]
@jalew188 is my colleague 😃, the issue arises in a shared codebase.
Do you think this could be a packaging issue? I'm asking because of the different checksums.
