### ISSUE TITLE
NumPy 2.0 compatibility

### ISSUE THREAD

**Issue by DvdGiessen** [louisabraham/pydivsufsort#49]
I think the new NumPy 2.0 release introduced some compatibility issues. I'm getting the following errors (on multiple platforms) after running updating dependencies:

```
(...)
  File "/build/.venv/lib/python3.9/site-packages/pydivsufsort/__init__.py", line 2, in <module>
    from .stringalg import (
  File "pydivsufsort/stringalg.pyx", line 1, in init pydivsufsort.stringalg
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

That seems to correspond with breaking changes mentioned in the NumPy 2.0 migration guide:

https://numpy.org/doc/stable/numpy_2_0_migration_guide.html#functionality-moved-to-headers-requiring-import-array

Workaround for now is properly pinning the NumPy package to an older version (`numpy==1.26.4`).

**Comment by louisabraham** [comment]
Hi, I couldn't reproduce with numpy 2.0 on my mac. However, I added a line `np.import_array()` that doesn't seem to hurt even on numpy 1.26. Can you try with the latest version (0.0.15) that is getting uploaded?

**Comment by louisabraham** [comment]
ok, seems like I have build issues because of numpy... Trying to resolve them

**Comment by louisabraham** [comment]
The key was here: https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice
We precompile using `numpy>=2.0` now.

**Comment by DvdGiessen** [comment]
I can confirm the issue has been resolved in my quick test on macOS and Linux. :)
