### ISSUE TITLE
Add Optional Unit Test For Large Inputs

### ISSUE THREAD

**Issue by seanlaw** [louisabraham/pydivsufsort#7]
@louisabraham Would it be helpful to start writing unit tests or would it be premature/overkill? I could possibly help with this if you want to provide some guidance on what needs to be/should be tested. I typically use `pytest`

**Comment by louisabraham** [comment]
Look at the README :)

**Comment by louisabraham** [comment]
What worries me is the need to test for inputs larger than 2**31 (thus needing divsufsort64). This is not something anybody can do so I don't want to include it in the tests.

**Comment by seanlaw** [comment]
> Look at the README :)

Ha! Glad we're on the same page

**Comment by louisabraham** [comment]
Could you write a test for huge inputs and execute it?
There is probably a way to specify some tests as optional in pytest.

**Comment by seanlaw** [comment]
When you say `2**31`, are you saying:

```
inp = np.random.randint(2**31, dtype=np.uint8)
```

Is the goal to actually verify the output or only to ensure that the input can be handled? 

To handle the long/slow running tests, we can skip them from the command line according to [this documentation](https://docs.pytest.org/en/latest/example/simple.html#control-skipping-of-tests-according-to-command-line-option)

**Comment by louisabraham** [comment]
That's precisely the issue: in theory, I would have to check the result. However, I don't think we should lose too much time on that.
There is a function in libdivsufsort to check the result, I'll implement it later (#11) so we don't really to check correctness.

**Comment by louisabraham** [comment]
That's probably overkill. The original code is the same for the 32 and 64 bits versions, with just some flags changing.
