### ISSUE TITLE
How can we support OpenMP?

### ISSUE THREAD

**Issue by louisabraham** [louisabraham/pydivsufsort#8]
Compiling with `-D​USE_OPENMP` is easy.
However if we use it in the bdist_wheel the people without OpenMP will have an error.
Compiling both (thus having 4 dll) is possible, even though it adds some bloat.

**Comment by seanlaw** [comment]
At this point, I don't think I'm too concerned. The lib files look pretty small. Maybe you have a different idea but anything less than 1MB is perfectly fine (I'm guessing that we'll come in at under 250-500 KB even with wheels included). It's certainly worth the convenience if it isn't too much work to handle

**Comment by louisabraham** [comment]
After checking, I think OpenMP is almost always present so I activated it.

Computations are faster for large strings but slower for small. However,
setting `OMP_NUM_THREADS` yields the same performance as the version
without OpenMP so it's a win-win.

Le jeu. 27 févr. 2020 à 13:50, Sean M. Law <notifications@github.com> a
écrit :
