### ISSUE TITLE
Add Linting/Code Formatting

### ISSUE THREAD

**Issue by seanlaw** [louisabraham/pydivsufsort#9]
@louisabraham Would it be useful to add `flake8` and `black` for linting and code formatting, respectively?

Perhaps, this is something we can do later once Travis CI is in place

**Comment by louisabraham** [comment]
Yes, the current code is formatted in black. I have never used Travis for linting or code formatting.

**Comment by seanlaw** [comment]
Neither have I but I can only assume that it must be possible. I currently perform linting/code formatting **checks** on Azure Pipelines before accepting any public PR. While it is possible to automate it,  I haven't gotten to the level

**Comment by louisabraham** [comment]
It is now done on travis. I also added code coverage reports as a bonus

[![Coverage](https://codecov.io/gh/louisabraham/pydivsufsort/branch/master/graph/badge.svg)](https://codecov.io/gh/louisabraham/pydivsufsort)
